// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SY0tfNlE-P7Yak3S6w4DNvTYlpgu4OE',
    appId: '1:929110150017:web:bf97d7c8495b643952f680',
    messagingSenderId: '929110150017',
    projectId: 'teampro-98c11',
    authDomain: 'teampro-98c11.firebaseapp.com',
    storageBucket: 'teampro-98c11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvPgFhfN72aX1_2bmHNxFiVaQ5NqErCU',
    appId: '1:929110150017:android:308ffad28dd19f9052f680',
    messagingSenderId: '929110150017',
    projectId: 'teampro-98c11',
    storageBucket: 'teampro-98c11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqR1ZTVcuxadCIIWp3HFgPqLxTMPF7iR0',
    appId: '1:929110150017:ios:051af07ae101c9ba52f680',
    messagingSenderId: '929110150017',
    projectId: 'teampro-98c11',
    storageBucket: 'teampro-98c11.appspot.com',
    iosBundleId: 'com.example.teamPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqR1ZTVcuxadCIIWp3HFgPqLxTMPF7iR0',
    appId: '1:929110150017:ios:051af07ae101c9ba52f680',
    messagingSenderId: '929110150017',
    projectId: 'teampro-98c11',
    storageBucket: 'teampro-98c11.appspot.com',
    iosBundleId: 'com.example.teamPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2SY0tfNlE-P7Yak3S6w4DNvTYlpgu4OE',
    appId: '1:929110150017:web:78ef7511e70c309a52f680',
    messagingSenderId: '929110150017',
    projectId: 'teampro-98c11',
    authDomain: 'teampro-98c11.firebaseapp.com',
    storageBucket: 'teampro-98c11.appspot.com',
  );
}
